/** The source-neutral STRUCT document schema and its public document types. */
export {
  LEGACY_STRUCT_SCHEMA_VERSION,
  STRUCT_SCHEMA_VERSION,
  type StructAsset,
  type StructAssetKind,
  type StructBlock,
  type StructBlockKind,
  type StructBox,
  type StructDiagnostic,
  type StructDiagnosticSeverity,
  type StructDocument,
  type StructEvidence,
  type StructFurnitureEvidence,
  type StructFurnitureReview,
  type StructInline,
  type StructMetadata,
  type StructPageLayout,
  type StructReceipt,
  type StructRecovery,
  type StructRelationship,
  type StructRelationshipCandidate,
  type StructRelationshipKind,
  type StructRelationshipStatus,
  type StructSchemaVersion,
  type StructSource,
  type StructSourceFormat,
  type StructTable,
  type StructTableCell,
} from './types.js'
